[xray]
repo = "XTLS/Xray-core"
binary = "xray"
service = "infiproxy-xray.service"
active = "/opt/infiproxy/cores/xray/current"
config = "/etc/infiproxy-cores/xray/config.json"

[sing_box]
repo = "SagerNet/sing-box"
binary = "sing-box"
service = "infiproxy-sing-box.service"
active = "/opt/infiproxy/cores/sing-box/current"
config = "/etc/infiproxy-cores/sing-box/config.json"

[hysteria]
repo = "apernet/hysteria"
binary = "hysteria"
service = "infiproxy-hysteria.service"
active = "/opt/infiproxy/cores/hysteria/current"
config = "/etc/infiproxy-cores/hysteria/config.yaml"

[tuic]
repo = "tuic-protocol/tuic"
binary = "tuic-server"
service = "infiproxy-tuic.service"
active = "/opt/infiproxy/cores/tuic/current"
config = "/etc/infiproxy-cores/tuic/config.json"
