//! Owner-only secret-store presentation.

use crate::{admin_bar, csrf_field, ui::layout, AuthenticatedAdmin};
use axum::response::{Html, IntoResponse, Response};
use maud::html;
use stealthhub_core::{adapter::ProtocolRegistry, models::ProtocolProfile};

pub(crate) fn render(
    auth: &AuthenticatedAdmin,
    secret_names: &[String],
    profiles: &[ProtocolProfile],
    registry: &ProtocolRegistry,
) -> Response {
    Html(
        layout(
            "Secrets",
            html! {
                (admin_bar(auth))
                h1 { "Secrets" }

                div class="status-strip compact-status" {
                    div class="metric" { span { "Stored" } strong { (secret_names.len()) } }
                    div class="metric" { span { "Values shown" } strong { "never" } }
                    div class="metric" { span { "Access" } strong { "owner only" } }
                    div class="metric" { span { "Storage" } strong { "SQLite" } }
                }

                section {
                    h2 { "Create or rotate" }
                    div class="notice" {
                        "Saving an existing name rotates its value. Stored values are never returned to the browser after this request."
                    }
                    div class="notice" {
                        "Server-only private material is rejected here. Manage those references through " code { "sudo infiproxy-manager" } "."
                    }
                    form method="post" action="/admin/secrets" class="form" autocomplete="off" {
                        (csrf_field(&auth.csrf_token))
                        label {
                            span { "Secret name" }
                            input type="text" name="name" minlength="1" maxlength="128" placeholder="xray.reality.public_key" required;
                            small { "Letters, digits, dot, underscore and dash only." }
                        }
                        label class="full-span" {
                            span { "Secret value" }
                            textarea name="value" rows="4" maxlength="8192" required autocomplete="new-password" spellcheck="false" {}
                            small { "Use the exact client-side value generated by the matching server runtime." }
                        }
                        button type="submit" { "Store secret" }
                    }
                }

                section {
                    h2 { "Stored names" }
                    @if secret_names.is_empty() {
                        div class="notice" { "No protocol secrets are stored." }
                    } @else {
                        div class="table-wrap" {
                            table {
                                thead { tr { th { "Name" } th { "Used by" } th { "Remove" } } }
                                tbody {
                                    @for name in secret_names {
                                        tr {
                                            td { code { (name) } }
                                            td { (profile_usage(name, profiles, registry)) }
                                            td {
                                                form method="post" action="/admin/secrets/delete" class="inline-form" {
                                                    (csrf_field(&auth.csrf_token))
                                                    input type="hidden" name="name" value=(name);
                                                    input type="text" name="confirm" aria-label=(format!("Type {name} to delete")) placeholder=(name) required;
                                                    button type="submit" class="danger" { "Delete" }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
        )
        .into_string(),
    )
    .into_response()
}

fn profile_usage(name: &str, profiles: &[ProtocolProfile], registry: &ProtocolRegistry) -> String {
    let names = profiles
        .iter()
        .filter(|profile| {
            registry
                .get(&profile.protocol_id)
                .and_then(|adapter| adapter.secret_references(&profile.config).ok())
                .is_some_and(|references| {
                    references
                        .iter()
                        .any(|reference| reference.as_str() == name)
                })
        })
        .map(|profile| profile.name.as_str())
        .collect::<Vec<_>>();
    if names.is_empty() {
        "unused".to_string()
    } else {
        names.join(", ")
    }
}
